authorName: ZHANG Shuyu
experimentName: example_mnist_pytorch
trialConcurrency: 2
maxExecDuration: 1d
maxTrialNum: 1000
#choice: local, remote, pai
trainingServicePlatform: local
searchSpacePath: search_space.json
#choice: true, false
useAnnotation: false
logDir: /home/shuyu/nni_experiments
tuner:
  #choice: TPE, Random, Anneal, Evolution, BatchTuner, MetisTuner, GPTuner
  #SMAC (SMAC should be installed through nnictl)
  builtinTunerName: TPE
  classArgs:
    #choice: maximize, minimize
    optimize_mode: maximize
trial:
  command: python3 Revised.py
  codeDir: /home/shuyu/
  gpuNum: 1
